config/routes.rb
Rails.application.routes.draw do
  # get 'bookmarks/index'
  # get 'lists/index'
  # get 'movies/movies'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy

  # get '/movies', to: 'movies#index'

  # get '/lists', to: 'lists#index'
  # get 'lists/new', to: 'lists#new', as: :new_list
  # post 'lists/:id', to: 'lists#create'
  # get 'lists/:id', to: 'lists#show', as: :list

  # get '/bookmarks', to: 'bookmarks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, :list, presence: true
  validates_uniqueness_of :movie_id, :scope => [:list_id]

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.delete
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.delete
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a Movie</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit comment", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container d-flex flex-column p-3 justify-content-space-between">
<div class="border-bottom border-1 p-3 border-dark">
  <h1>My List</h1>
</div>

<ul>
<% @lists.each do |list| %>

  <div class="card-category my-3">
    <li><%= link_to list.name, list_path(list) %></li>
 </div>

  <div class="p-1">
    <%= link_to 'Delete list', list_path(list),data: { turbo_method: :delete, turbo_confirm: "Are you sure"}  %>
  </div>

<% end %>
</ul>

<br>
  <div class="border-top border-1 p-3 border-dark">
    <%= link_to 'Create a new list', new_list_path %>
  </div>

</div>

app/views/lists/new.html.erb
<div class="container p-3"
>
  <div class="border-bottom border-1 border-dark mb-3">
    <h1>Create a list</h1>
  </div>
<br>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/lists/show.html.erb
<div class="container p-2">

<h1 class="border-bottom border-1 p-3 border-dark"><%= @list.name %> movies</h1>

<div class="movies d-flex border-dark border-bottom border-3">
  <% @list.bookmarks.each do |bookmark| %>

  <div class="card m-2 border border-dark border-1 shadow p-2 mb-5 bg-body rounded" style="width: 18rem;">
    <div class="flex-shrink-0">
      <img src="<%= bookmark.movie.poster_url %>" width="300" height="300" class="card-img-top" alt="...">
     </div>

      <div class="card-body">
        <h5 class="card-title"><%= bookmark.movie.title %></h5>
        <p class="card-text">Overview: <%= bookmark.movie.overview %></p>

        <div class="d-flex">
        <p><strong>Rating:</strong>

          <div class="full-stars" style="color:#F4CE14"><%= "★" * bookmark.movie.rating.to_i%></div>
          <div class="empty-stars"><%= "☆" * (10 - bookmark.movie.rating.to_i) %></div>

        </div>

        <p><strong>Comment:</strong> <%= bookmark.comment %></p>

    <a href="#" class="btn btn-danger"><%= link_to 'Delete', bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure"} %></a>

      </div>

  </div>
  <% end %>
</div>

<br>

<%# <%= link_to 'Add a movie', new_list_bookmark_path(@list) %>
<div class="d-flex flex-column bd-highlight">

  <div class="form">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment %>
        <%= f.submit "Submit comment", class: "btn btn-primary" %>
      <% end %>
      <br>
    <%= link_to 'Back to lists', lists_path %>
  </div>


</div>

</div>